/*
 * PackageDeployment.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using PackageDeployment.Standard.Controllers;
using PackageDeployment.Standard.Http.Client;
using PackageDeployment.Standard.Utilities;

namespace PackageDeployment.Standard
{
    public partial class PackageDeploymentClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public PackageDeploymentClient() { }
        #endregion
    }
}