/*
 * PackageDeployment.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PackageDeployment.Standard.Http.Client;
using PackageDeployment.Standard;
using PackageDeployment.Standard.Utilities;


namespace PackageDeployment.Standard.Exceptions
{
    public class BadRequestModelException : APIException 
    {
        // These fields hold the values for the public properties.
        private string language;
        private string success;
        private string error;

        /// <summary>
        /// Language whose SDK was being published
        /// </summary>
        [JsonProperty("language")]
        public string Language 
        { 
            get 
            {
                return this.language; 
            } 
            private set 
            {
                this.language = value;
            }
        }

        /// <summary>
        /// Was the package successfully published
        /// </summary>
        [JsonProperty("success")]
        public string Success 
        { 
            get 
            {
                return this.success; 
            } 
            private set 
            {
                this.success = value;
            }
        }

        /// <summary>
        /// Error if any occured
        /// </summary>
        [JsonProperty("error")]
        public string Error 
        { 
            get 
            {
                return this.error; 
            } 
            private set 
            {
                this.error = value;
            }
        }

        /// <summary>
        /// Initialization constructor
        /// </summary>
        /// <param name="reason"> The reason for throwing exception </param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects </param>
        public BadRequestModelException(string reason, HttpContext context)
            : base(reason, context)
        {
        }
    }
} 